# https://rosalind.info/problems/dna
dna = "CATTCACATTGATGCCTCACACAATGTGAACCGCTTACTTTGCAACTTCAGTAAGAAGCTAACTTTTTACAAATAGGTGCTACAATATCAGTACATTGGCAGTACGTTCGGTACGGTCATTAACGATAATCTAGTGACTGTAGGGGTTTCCCTCGTAACTCGCCGCTAGGGCTAACGATCAACAGCCGCTCATCACGGCGCCAATAGCACGGTTACTCAGCCTCCTCTAATTCTAAAAGCATCATCCCGCCACGATCTTACCCTCGACTATTGCAAGGCACCATACGAAGAGGCTTCCAAATACGGTACAATAGCATCTGTCACTTAGTCACCTTGAAGGATTTCGTCTGGGAATACGTCCATGAAGTGTCCACCCTAACGAGAATCTAATCCCTTGAATGACTGAAAGGCAGGCTTACGAAACGCGATCGGTTAGTGCAACGTTACAACTGCCCTTTGAGAGAAAGAGCCGCAATAGGTTAAGATACTTGGAAACAGGGATGCTGTCATCTTGTCTTGGAGAGGCACCCCTAGGACATGCTTCATCTTCTACAAAAAGAGGTCCAATTACTACAAATCAGCCCGAGACGAAAGCTTAACCTGGAGGAGTTGCCTCAGTGACCTGCGAATTATGGGTGACAGCTATGGCCTAAGGCAAGCCTTGCTCCGGCGGGCTCGCGCATTTGCGATGCTGCCTGCACGTCGGTGATCTAGCGAGAGTGCAAGAACAGGTGCGCTCGACGGATATTGCCCCGTTTCGGACTTACACCTCCCGAATGAACGTCGACTGAAGTAGGTCCATCAGACGGCGGTCAGCTGAAACGCGCGACACACGCGCAATTGGGTGACAAGGCGCATTTGAACAGCAACAGGAAAGTTAGAGTCCGGAGTGTTAACGA"

def test(dna):
  hash_map = {}

  for char in dna:
    if char in hash_map:
      hash_map[char] += 1
    else:
      hash_map[char] = 1

  result = []
  
  if 'A' in hash_map: result.append(str(hash_map['A'])) 
  if 'C' in hash_map: result.append(str(hash_map['C']))
  if 'G' in hash_map: result.append(str(hash_map['G']))
  if 'T' in hash_map: result.append(str(hash_map['T']))

  return ' '.join(result)

counts = test(dna)
print(counts)