# https://rosalind.info/problems/prot

'''
RNA codon table

UUU F      CUU L      AUU I      GUU V
UUC F      CUC L      AUC I      GUC V
UUA L      CUA L      AUA I      GUA V
UUG L      CUG L      AUG M      GUG V
UCU S      CCU P      ACU T      GCU A
UCC S      CCC P      ACC T      GCC A
UCA S      CCA P      ACA T      GCA A
UCG S      CCG P      ACG T      GCG A
UAU Y      CAU H      AAU N      GAU D
UAC Y      CAC H      AAC N      GAC D
UAA Stop   CAA Q      AAA K      GAA E
UAG Stop   CAG Q      AAG K      GAG E
UGU C      CGU R      AGU S      GGU G
UGC C      CGC R      AGC S      GGC G
UGA Stop   CGA R      AGA R      GGA G
UGG W      CGG R      AGG R      GGG G 
'''

rna_codon_table = {
  'UUU': 'F',
  'CUU': 'L',
  'AUU': 'I',
  'GUU': 'V',
  'UUC': 'F',
  'CUC': 'L',
  'AUC': 'I',
  'GUC': 'V',
  'UUA': 'L',
  'CUA': 'L',
  'AUA': 'I',
  'GUA': 'V',
  'UUG': 'L',
  'CUG': 'L',
  'AUG': 'M',
  'GUG': 'V',
  'UCU': 'S',
  'CCU': 'P',
  'ACU': 'T',
  'GCU': 'A',
  'UCC': 'S',
  'CCC': 'P',
  'ACC': 'T',
  'GCC': 'A',
  'UCA': 'S',
  'CCA': 'P',
  'ACA': 'T',
  'GCA': 'A',
  'UCG': 'S',
  'CCG': 'P',
  'ACG': 'T',
  'GCG': 'A',
  'UAU': 'Y',
  'CAU': 'H',
  'AAU': 'N',
  'GAU': 'D',
  'UAC': 'Y',
  'CAC': 'H',
  'AAC': 'N',
  'GAC': 'D',
  'UAA': 'Stop',
  'CAA': 'Q',
  'AAA': 'K',
  'GAA': 'E',
  'UAG': 'Stop',
  'CAG': 'Q',
  'AAG': 'K',
  'GAG': 'E',
  'UGU': 'C',
  'CGU': 'R',
  'AGU': 'S',
  'GGU': 'G',
  'UGC': 'C',
  'CGC': 'R',
  'AGC': 'S',
  'GGC': 'G',
  'UGA': 'Stop',
  'CGA': 'R',
  'AGA': 'R',
  'GGA': 'G',
  'UGG': 'W',
  'CGG': 'R',
  'AGG': 'R',
  'GGG': 'G'
}

def prot(rna_string):
  amino_acid = []

  for index in range(0, len(rna_string), 3):
    amino_acid_segment = rna_codon_table[rna_string[index:index+3]]

    if amino_acid_segment == 'Stop':
      break
    else:
      amino_acid.append(amino_acid_segment)

  return ''.join(amino_acid)

def prot_list_comprehension(rna_string):
    return ''.join(
        rna_codon_table[rna_string[index:index+3]] 
        for index in range(0, len(rna_string), 3) 
        if rna_codon_table[rna_string[index:index+3]] != 'Stop'
    )

print(prot('AUGGCCAUGGCGCCCAGAACUGAGAUCAAUAGUACCCGUAUUAACGGGUGA')) # MAMAPRTEINSTRING
print(prot('AUGAGCUCUAAUACCCCUGUCCCACCAUGCAUGUAUCUGGGAAUGGCCCAGGUUGGUGACCGGUUUAGUGGGGAGUUACGCGCGCCCCCCGAUCAAGCUAUGUCGCGCCGUACUUUGACAGGAUCAUUCAGGGGGUCGAGUGGGGUUGUCGCUACCUUGAACCAUUUCGAUCUGACAUACAGAUCAGGGGCAGUAUUUUUAACGUUAUGGUAUGGUGGAAUCUCCGUGUCACUAUUGAUCACUAAGAGGACGGCGGGGUGUGUUAGUUUAGCUUCCGGGAGUCGACGUAACGCGGCACGCAGCAGUAGGCAGAAUUUUGCCGCCUACUUCCACGGACGUACUGUCAUUAUAACAACGACCAUGGACGCCCAGCAGAUGUCACUAGUGGAGGUAAUCAGAUUCUACGGGACUGGCAGCGCGGCCAGGGCUGGGCCGGUCUUCCGUUGCCCCUCCAGUUCCCAGGAGGUAGCGCUGUUCUGGGACUUUGGCACAUUGUGGUCUAUGGUAGGUUGUCUAGCCACUGUGUGUCGUUUAGUAUUUGCGCGGGGAGCCCUCGACAGUAAGGAAGACUUUACAGGGUUCGGCCGACUGAAAGCGAGCCUUACCACUUGCAGGAUGCGUGCUUCCCCCUUCUGUCUCGUCGCACAGCGAACCGCCGGGUACCCGCAGAGUCCGCUUGCAGGACUGACGGGUCGAAAGUUGCCUGGUAAUAUUCCGAAUAAGAACCAAUUUAGGUCUCGAGGUGAUCAUGACACGAUAAAGCCCCGGCAGUAUUAUCACAUGGCUUCGUUCCUAACGUUAGUUUAUCCUCCCGACAGACUACCUUCAACCUGUAGUGUUUGUAGAGAAAGUGGCGCUAUUCAGAGUCUAGGGCACGUACCCAUGUCCGAUAUCCUUAUGUGCGGACAUCGGUGCAACGGACACCGUCAUGCCUGCCAUGAGCCCGCCUAUAGCAUUGCGAGGUUUCGGCAGCAUCGAAACAGGUUCAGUUCGAUACUGUUCAACAGUCCCAGCUUAAUAGCCGGCCCCAUCGAGAGCUCUGACCUCGCUGCAGCGCCGGAUCAUAUUUACAGACAUCAUGCAAACCCUUCUCAAAACCGGGCCGAUACAACUUUUGCACUUCACUUUGAACCGUUAUCUCUUCCGGCUACAGGCCCAUGGGGGACUGGGUCUACGAUUAACGAGACCGACAAACGGAGCAUGUGUCGCACAUGUAGUAUAUUCAUAAGGCCGGCUGCCGUCAACUCAUACUUGACACCUGUUCAUGGUUUUACCACCAAGCAUUACGCGCCUCGCUACAGUGAGUGCCCUAGCGAGGUCGCGAUGCGUCCCGACACCAGUCUCGCCCCAUAUUGCCGAUGCUCUAUAAUACCUUGCCGGAACGAAGACUGUAUGGUUGAGAAAGUCGCUCUGCGAGACUUACUACCUCACCAGCCCCCUUGGUGGUGCCCCCUUAUACCUUGGAGGGAUUACUAUACGCGCGCUUGUUGCUGGAAGGUGAAGCAAGGCGACUUUGUAGAGGCGGUCGUGCCACAUAGUGGACUUCGCAAACCUAAGCUCAGCCACAGGCGCCCUGCGGUCCUGUCUGCAUACCUCCCGGUGCCGCAUUCCCCCGGUCGGGACCCCGGCUCGUCGUCACGGGUCCAGAACGCCAUUCCUGCCACGUCGAUGCUUUCAACACCCACGCAGACAGGCAAGGGUUGCUGGAAUGGACGGGCGUAUACAACUGGGGUCUGGUCGAACGGCUACAUGGCGUAUGCUCAACUGGGAGGUGUAAGUCAUAAGAGCAUAUUCUACCAGGUUGUAUAUUCAACAGGAUCCACAUCGGCUGGGCGUUACCGUCCCAUGAUACACCCUUCGGCUGCCAUGCAACAGGGAAGCUUCCCUCAUGUGGGUGUGACAGGAGUCAGUGAUCGUAGUCCAACAAUAUGUGCCGGAUGUAAGCUCUAUUUGCCGUCUUUUCACAAUCAUAUAUUUUACGGUAAGGAUGGCCAGUCUAUGCGACUGCGUGCUAUCAUCCGAUGGGCGCCUCGUAGCCUCAUGGGACAUAGUUUUAUAAAAGUCGCAGUAAACUCAGCGCCACCCGCCUCAUAUCUUCUAGAGGCCGGCGGUAGUCGAAUGAAUGGCAAAGGUAUAACCUUGCAUUCAACCGUUACACGCUUAUCGUGUAGGGGACUCUCCGAAAGUAUUAGCCGAACUAAUUGUACAUUUCUAGGCUUAAAGCUGUCCCAAAUUCAGCAAUGUCUAAGGGCACGGGGUGCUGAAAUACGCGUCACACUUCGUUGCGCGACCAAUAUAGAGAACUGCUCAAUGAUCAACACCAUAAGAGACACCUGGCUCUCCGAAGUGUUGGCCGUAGUGAGCUGGGACCCUGCACCUGUAGACACCUGCGUCGGGCACCGCCAUUUCCCAGGCGGCCGGGAGGCCCCGGUUGGCAUACUGCGUAACGGCCAUUCUAACACAGCCGAUCCCCCACUAUGUUUAUGGAAACGCGGUCCCUCGGCACUCACCAGCGACUCCGGCCAACUUCGGGAGGAUAACGUGGUAGCAGUUGGAGGAGCAGAAUCGCCCAAACAUCGGCAGUAUAAACGUGGCGUGCCCGGCGUCAAAAGCGAUCGUGCCGCGCCUCGCUGCGUUGUGCAUCUUUCUCCAGGCGUGGUGCUCCGGCGGUUCAUUAUGCUAUCAUCCGCGGAAUUCUCCUCCCUGACAUCUCGAUGGAUUUACACUCGGUCCAGCACUGCCUCUCUGUGGUCAGUAGACCAUCUUAGACCUUCUAUGACUUCGACCACGUCUUUAGAUAGUAACAGCACCCGAAAGUAUAUUCAAUUCCAUGGGGGACACCCUGUAAUCCACCUUGUUUAUCAGGCAAGUCACGGUACGGCGCCAUUUCGGGUAAUAACUGGCGUGUCUAAUUGCUUCCUGAGCCAAACAGCUCUAACAGAUGGCGCUCCUGCCCAUCUAGCUUGGCCAUUCAAUUGUGGAAUUACAGUCGCGCAGAUCGUUAUGCGUCUACCGGAUUCGGGUAAGGCGUUACGACUACAUUAUGUGUCUCAUCGCCAUCCAGAGGCAACUUUUUCCGUGCAGGGACACGGACGUUCGCCUCUCUUCACAAAAACAGGCAAUAGCCAAAAUGGCUUAGUUAGCAUGUGCGCUACUAUCUUCCGGAGAAGUGAGCGAAUUCCUCUGUCGAGUCCACCUAACAGACAUAGACCGAAUUCUCUAUCAAAAGAUAGCACUCAGCGUCUCACCACGAAGAGCUGGUCUCAACCUGCCAUGCAUUAUACAGAAACAAGUUUCCUUCGACUACGAGGUAAUAUUUGCCAUCCCGACCUCUCUAUGAGUGCAGCCACACAAAGUACCAGGAAAAUGUCCCUCGUCUACUACUGGCAGACGGUUCCCAAGGGGUACGAGAAACUCUCGUGCAACACACGAGGGUGUUGGGUAGCUGUUCUCAACCACCACAGACGCUUAGGUCGGCAGAGAUUAAUCCGCGUUGCUCGCAUACCACGAAUCUCCCAGCCUUUAAAUGUAUACUUGAACCAACGGUUGCACUAUAAGGCCAUCUGUAUCUCCGUGGUAAACUACGAAUUACUACUCCAGAAGAGCAGGAGAGGUUCUGGUUCCGUGAGAGGCAUGACAAAAUGUGUUCCGCUCCCGGCAUACACUCAAGGAUCCUGCUGCCGUGCAUCAAAAAAAUAUGGGUGUGUCACGCUGGCGUGGUGGGGCCUAAUAACCCUUCAGCCUAAUUUAGUCCGCUAUGUUGUCGUAGGCAGCUUGCGUUACUUCUGGAAUGAGUGGCAUUCUGGUCUGUUCACUUCUUGCGCGGUAGAACGCUUGUGUGCUUUGUGUCUGUCGCAUCUGACCUUACCCGUUGCCCCACACAAUUUGCUUCAUAUGGAGGUCGGUACUCGCAAUACAGGUGCGAUUAUGUACGAGAUCUUGCGAGAAUCUCCGAGGUUUUUUAUCGAGAGGCAGCCAAGGGGCCCUGAUCAUAUACUUUUACUGUCGCCACUUCACAGUUACAUAAAAAUACGUAAAUCUAACCCGUCGGAACGCCCGUGUUUGACCCUAAACAAAAAUAGUUAUCAGCCAAUAGCGUUGAUUGGGAUGAUGCGGAAGGGUGGCUUCGCACACUGGCGCAGCGAUAAGGCAGCUCAGGUUAAGGAGCUCGUUAUCCAUUGGUUCAUACGUCGGCACUGGCGCGGCUGCGGUGGUUGCACCAUAAUUUCUGACGGUCCCAGAACUAAGGUGAGUCCGGUACAAGAAACAGAGACAUUUCCCAUCCCCUCCUGGAACGUUUCACAUAUAUAUUCGCGCAUACGGAGCGUAGUAGGAAAAAACUAUCAUGCUGUGGUGAUAAUACAACUCCGCUCUGACGAUUUACGCCCCACAGGAACCAGAAAGGGGUCGCAACCGGUCUAUAGGUGCUAUAGCCAGUAUCAUGGCGGGGCCAUGGAGUUAGGAAUUCGGCAGCAGCGGCGAGCGUCCUCCAAGACACAGCGGGAGAACAUGUCAGUGUACCACUGGGAAUUAGCCGAAGCCAAAAGAUUUAGUUCCCGACCGGACCAGGCUUUACUACUCGCCGUGGUUAGUGCAAGCGGAACAACGACGAGCAGUACUCGUGGACUACAGAUAGAAAGGCAGCCUGUCUUCCAUAUCAGGCAUAUCGGCAAACUCGUGCUGGCCAGUGCUCCAUCAACGGGUCCAGGAACCCGGCGACUUCCAAUAGAUAGAGGUCCCUCCUUCACGGAACUUAUACUUUUUAACCAAUCUAGGUUGUCUAGAAAAUUUCGAUUAACGGUCAUUUACAGGUCUUCCGUAAUCUCCAUUGGGUCCAAAGCCCUUCUGCGGUUAGUGUCCUGGCUUGUAAUAAAGUGCCGAUGCGACUCACAGAGGUUCACGAAAGGCUUUAGGCAGCGCCGCACAGGGUCUCUCUUGAGUGGAACUCAUGGGAAAUUGCGAGCGCGCGUUGACUUGUGUUUCUCUUGCUUCUCCCAUUUGGGUGCACUUAGCUCCAUAGGCUUUACUCAACCGAGAGACCCGUAUUUUAUCCGGAAAGACGCCCCGAUGCAAACCUACGUGUUGAUCCUAGUAUCAUCCACGAUGCAAUUAAGCAUGUGCGUUUGGCCAGGGAGUACGAGCUCGGGGCGUUCCCUGAGAAUCUGCCCAGCACCUUGGGUAGUCACUCAUAUCCUAGGUGAGAUUGCUGGCCAGUUGCCAACAAAACUCAUCUCCCCACUACUUCCCGCGCAUUAUUUCAUGCGACGUAGGGAUCUAAGUCGGAAUGCCUGUAUAAAAGAUAUGCGCAAAGGAGUUUGGCAUAGGGCUGCCAACGGAAAUCUUAGCUAUCAAGGAGUAAAAACACUACGCGUCCGCGUGACUUGCGUCCAAGGGUCGCAAGAGGAGCUUCGGUGGUUUAGACUUCGCGGGGAAGACGUGACCUCAUCGGGUAUGGCCGGACCCCUACUAUACCCAGUUUGGCAAGGAUCGUACUGUCAACCGAUACACGGAUUGGUCGUAGAGCGGGAUCAGUUAUUUCUGCCCCCGUUCCACUCUUUGAACCCGAAAAGUUUGCCGAAUACCGGAGGCCGUAUUAGAGACUGGGUGAUGAUAGUUCAGUACUAUACUCGUGAUGAGGCGGAGCCUUUGUCGGCCAUCUGGCGAACUCCGAAACUAGGUUAUCCUGCGAACCAGUUGUAUGUUGGGGGUCGCGUUAACGUAUUUAAGUAUCACUUAGACCCGCAGAUAAUACCUGUGACAAACUCACCGAGGGACAUUGUUCCUGCACUUUCGUCACUUGUAGAAUCAUGUUUGGAUCGUUUGACAUGCCGCUCCGGCCGUACCCAUAUUAAAGGAGGUAGGCGCUUCAGACCUUACUUUAUUAGAAUAAGUUUAACACGGGUAAAUCGAGAUGUACUGAGCCCGCCUGGCCACUAUCUCCUAGAUUUACAUACAGAAUGGUGCUGUACUCGAAUAGUUGGACUUAAGAUAGCGCUUAUCUCCGAACGCAUGAAUAGCGAGGCACCGGGCUUCCGAGGGGCUGUAACAGAAACGGUAUCCAAAGAUCAGCCCCCUAUAUUGCACCUGGCGGGGCACCGGCUCACCUACCUGGCAACCGCGAUUUUAAAGAAUACAUCUCUCGCUAAUUCGACGUUAGAAUCAUUGCGGCGCAAGUUCCUUGGGCGCCAUCAAUCUUAUUCGCCGGUGAGAAUGCGUUCUGGCGUCUUGGCAAUUCUACUGCCGUGCAUCUUCCAGAGUGCUAGUAUAGGAGUCACUUGGUUGUCGACUCUGAAUACGGUUUGGUUGAUACGAUAUAUAUGCCCGGGAAGAUCAACAAUGUCACUCGAUGUCUUCUUAUCACACAGUGAUCAGGAUCAGGUGCGCCACACUGACCAAUCUAACCCUAUGUCGGCGAGAGUAUGUAAGUCGGCAAGGCCACCCCUGCCCUGUGGAUCUCCUGCUACAAUACGUCACGCACGACAAGCGCAGCAGUUCACGGACUCAUGUCAUCCUCACUCUUCCAGCUUGAAUAGAAUGAUAUCGAAAUCUCCGGUAUAUGAACCAACGAACGUCCAGACCAUAGCUCACAUUGGGUUGAAUUUCAACCACCAGGUAAGCGCUCCCUGUGCAGAGCGAGUAGGACGGCCAGCGUGUUAUAUCUAUUUGACGAGAGCGAAACAGGCUAGCCAGUCUCCCGGCCAUCUUAUGCCAAUAAACAUGCGAGGGGAAGAGAGGUUUGGUCGCGGAGUACUAGUUAGUCUUUGCAUAUCCACUACGUCUAGACUCAGUAGGCUUUGUCUAAUUAGGAAGUCUCUGAACGACAAAGUCGAGCCCGCUUCCCGACGCAGGCACGCAGCUCUACGCCUAUUCCCAGGUUUGCGCGAUGGGUGCCCAGCUGCUCCGCAACCCCGUGAGAAAUAUAUGGCCACCAGCAUACUUCCUGACGCGGAGCCAGGGUUUGUAUGCCUCUCCUGUCUUAAUUCCGUCAGGAUAGCGUUGAUUCCUAUCAUGUGGUGCUUAUUGCACUCCACUGAUUUUCAAAUUGGAUAUACACCCUAUUGGGAGUUAGAGGAACCAGCACACCGAUCUAAGAUGGCCUUGAAACUCACCUGUUCGCUGGGCCAUGCUAUCGAUAUGUCAGGGCCUCACAUCAAGCUUGAAGGGCUGAAGUACGACACCGUCGCGGGUCGGUGGACCUCCCUACUAGCAAAUCCCGGCCCAGGUAUUUCAAUUGGUGAGCCCCGUCGGAUACUCGCAAUGCAUCCACAACUUAUAGGACUAUGUGAAGUGCACAUAUGCUGGGACGGUGCAAAUGAUGACCCAUCUCUCCAGUCCGUGGCGACCCGCGGGCCCCGUCCGUGGUUCAAAUGCCAGAACACCCGUAGUGACAAUUCUGUAGAUAGCCUUGUAAAGAUAGAGUCCUGGCCUCUUAAUAAAGCAAAAGCGAUGGCUGAGCAAAUGCCAGGCUGUCUAUCUUUCACUCAUGUUGUACGCCUGGGAAAUACAGCUACAGUGUCCGAAACCACCCGGUCAGUGAGACACAUGCCAACCCGUCCUGGGUGUGGACAAAUGAAUGUUAGCUACGCCGGCACGACACAGGGACGCAUAUCCAGUAGCCAAGUGAGGAUAUAUCGAUGGCAUUGUGAUGUCUUACAGGAUUGCCUUAUGAACAGGGCCAACGUAAUGCUCCUAAGCGAGGAACCAACCAGCACGAUCUUAUCCCGAAUUCUAGAGAUCGCGCUAACAUUGUACCACGACCGUAUUGUUUGGUGUAAAAGCAGCUCAGUAGUGAACAAAUCAAUUAUCUGCCCACCACCAUCGUCUAUACUCUUGGACCCUGGAAGUACUAGGCGCGUCGGAGGAUGUGUAGGAACCCUCCGGAAAACUAUAUUGGCAAUCUUCUCAGAGGGAGGUCGACAGAUGGUUGAAGAGCGCGGUCGAAGUCAGAAGUCUAGUAGAAGACGUGGCUUCCUCGUUUAUAUAAUGUGCGAAUGUGUACCACGUCGAUCGCGGUCGAUCUUACAUAUAGGGCGGGGCACACGACGCCCGCUAUUUCAACGCACGCGAUAUCCAGGCACUAGCUACUGGACCAAGGCAUUACUAAAUCUGGCCCGUUUAAAAGAAAACGCUUUCCGACCUAUCUGCACGGACCAGAACAACGCCAUUCGCCUUCGAGUGAGAACUUUCUCUCACAGAGUUCAUGAGCUCAGUACCAUUGACGAUUGUAAUUGCCCAAAAGGCGGUCCAUACACCCCAUUCAAAAAGGGUUCGCGAAUGCCGGCCGUCCGCCUGACAAUGUUAUGGUUAAGAGUUCAACAGAAACAGUAUUGUGGCAUCAGCACGUUAUUCAUAGCGGGCCGCUCCAGUUUAGCUUACUACCAAGAUCUGCGUAGGGAUGCGCUGACGAUUCGGUUAGAUGCACCGGGUGUUCCCAGACCCGGGCGACAUAGCGCCCACGUUUUGCGGGGGGUAGCCAAAUUCCUGCGGAAUCGACUCCAACAGGUAGCGCGUAUCCACGGAUGCCCGUGUUGUCAUAGUCGCAUCCGCCCCCAGGUAAUCACUCGCGAUGCGCCUGACCUGUAA'))