# https://rosalind.info/problems/prtm

monoisotopic_mass_table_string = """A 71.03711
C 103.00919
D 115.02694
E 129.04259
F 147.06841
G 57.02146
H 137.05891
I 113.08406
K 128.09496
L 113.08406
M 131.04049
N 114.04293
P 97.05276
Q 128.05858
R 156.10111
S 87.03203
T 101.04768
V 99.06841
W 186.07931
Y 163.06333
"""

sample_dataset = 'SKADYEK'
another_sample = 'ACMDMTHLTLYSHSYWYKQQRSNGSGIWIQVKFPMHHVDGKLMSMRMGLFYFCGQPNNMALGEHGSHEKWINRSSARMELMKQIMFIRPVCGYISQMYAWSNRVRKWNAPLHFIKRAEMHEYDTFNIKGWWIRWTWMQKKMLFGHMEMWRIQPPGRSHEAMPDGNNDYKWCFANHWNQWDSSTQMCNEHCMGRWFKKTLFRTRSKHFGYCKEDTPYPTVRTMLYLTSKGKCYEYGCEIMVNKIFGEYNGKPHQECFSADVEDLLMDFFILANLVEMWMCVVYLSVYKDHYFYWHTMRIRISCYFHPGQDSGMFWAFFNIMFPWSLMYRCHYLFGPMLSCVYTGGHKDEMVKVGSWYVSHDVSAFKYWCKCKKFYMVLQMAMNVALQYSFYIKELRCPLTCANSCATIMQAYDDDDHRKQDNFWCGVTTQGNGGNHCSWKDAHNFIHFGALQPNCDSTTWHAKRMSEEYAWVKHADCMQTVALCMWMNYFMHAIGHVMCPYASPMCVVFDEQVRAVELFSINATTIMDQSFKYLYPCYRQPKRMMMEAYTEAARAEDKPFRWFSNLAHSSKHVKTLDVFLWFMFPETETTQLTTSEMVKAMAPDDTQHWLHGWGLNWLEHFQYGMEHGHEQQATLIHVMMHLCFIKFVWYCYSFTVMANHLAMFQAPDWPNVRFTPETEVRLRLYSREYVHISWTIFTARSYCRFAWNNRQVGPSQFQKHENSKQNVETCMTIIAYKKMHNILSNDPLQEQCLTWTEYFDECIRLRSHNKETLIAQCDSCSLQWGWVCEFAAGRIGFQTISPDTDLTINKGCFWSSYYQNSTFLSSTKRQRKVAWYECFNQIMNFFERTYEIVYWFEHKPRLYLKIPGTEVVIEMMNECNRLLVYQFYSGCDRHAVPLSRCRPTEVTSDCCLMVRRHVPHKYNKHHFSMKQFYITFLMCWCHHPAAAPYSHASSQCAYQMFSTDKSKHDIMIDQPEENGFCKIEWDMMDNA'

def parse_table(monoisotopic_mass_table_string):
  monoisotopic_mass_table = {}

  for line in monoisotopic_mass_table_string.splitlines():
    [symbol, value] = line.split(' ')
    monoisotopic_mass_table[symbol] = float(value)

  return monoisotopic_mass_table

def total_protein_weight(monoisotopic_mass_table, sample_dataset):
  result = sum(monoisotopic_mass_table[symbol] for symbol in sample_dataset)
  return "{:.3f}".format(result)

table = parse_table(monoisotopic_mass_table_string)
print(total_protein_weight(table, sample_dataset))
print(total_protein_weight(table, another_sample))