"""
Problem: https://rosalind.info/problems/rna
An RNA string is a string formed from the alphabet containing 'A', 'C', 'G', and 'U'.

Given a DNA string t corresponding to a coding strand,
its transcribed RNA string u is formed by replacing all
occurrences of 'T' in t with 'U' in u

Given: A DNA string t having length at most 1000 nt.
Return: The transcribed RNA string of t

- Sample Dataset: GATGGAACTTGACTACGTAAATT
- Sample Output: GAUGGAACUUGACUACGUAAAUU
"""

def rna(t):
  return ''.join(['U' if char == 'T' else char for char in t])

print(rna('GATGGAACTTGACTACGTAAATT'), ' = ', 'GAUGGAACUUGACUACGUAAAUU', rna('GATGGAACTTGACTACGTAAATT') == 'GAUGGAACUUGACUACGUAAAUU')
print(rna('CCGGAGGAAACAAGGGAGAACGAAGTTTGTGAACTAAGCTCAGTACCTGGCCAAATGAGCGTGGCAATAAGTATACTTTAGCTCGACAAAACCAATACGTGTCCAATCCAGAACAGAAGTGAATTGGTCTGTTGCATCCGGAATAGTGACTACATGAATAAGAGGTGACGCCGTAATCAGTCGGGCGGACCCGCTGCGTATTTCAACTTTAACGTGTAAGCGTCACCGGAACGGACAACTCCGACATTACAAAAAGGAGTGCGCAGTCAAATGGCACTACCTTGTAGACGGCCGCCATTCGTGGTAGATCTGCTGTTTAGTGTACCGCTAACATAGCCGGTTTAAGATCAGTCCCTTATCGGAGCCTACAGTAAAGAGGGTCTCAGTCCGCAAGAAGAACGTGGTTTTGTTGATCCGGCCGCAGAGGGGTGCTCCTGGAATTTGTGGAAAACAAGACGCTTCCTCTTCTTCCGCCAGTCTAAGCTCCCCGTCAATTCGATTCTCAAACTAGACCTGACTACCAGTGCGTCGTTGTCTGACTAAGCGGTGGCCACATTCCTAGTAACGTTTTTGGATCCTGAACCGGTACGGGGGAGCCTCATACAGAAGCATGACGTGTATTGGACATCTTATGGGCTGTCCCGGCCTTTTAGTTTGTAGCAAGGGGGACGCGTTCCGCTATATTCCAAGGAATTGCAACGCCCCGTCCGATGTATTTTCCTCCCCTGAGATCTCCGTGCTCTAGATGCCAACGTTCATTTTACAAACACTATTAATTTAAAGTGCAATGTACGACGGACAGAGCTGCGCCTTGGATAGTGAACTGGTGTCTCCCTGACAGTCCGTCTCCTATACTGAAGCTGGTAAGTGAATCACGACTCAGCCCCATTCGAACAGTTCTCGAGAGAAAAAATCTACCGATATTTAAAGCGCTTACTCCTGTTCATAGACCAGGATCTTGCCCAAGGC'))